<a href="https://colab.research.google.com/github/2017130744/-neowizard/blob/main/06%20python%20numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##numpy: 

import numpy as np
from numpy import exp  ##원래는 numpy.exp라고 써야하지만 from import를 통해 exp를 바로 가져올 수 있게 했다. 



In [4]:
#리스트로 행렬 표현

A = [[1,0],[0,1]]
B = [[1,1],[1,1]]

A + B  ## 이는 행렬합이 아니라 그냥 리스트연산을 한다. 

A = np.array([[1,0],[0,1]])
B = np.array([[1,1],[1,1]])

A+B     ##numpy를 써주면 행렬을 만들 수 있고 이는 행렬합의 연산이다. 
        ##행렬 자체는 리스트로도 나타낼 수 있지만 행렬 연산이 직관적이지 않고 오류 가능성이 높다. 따라서 numpy 사용은 행렬 연산을 위해 필수다.

array([[2, 1],
       [1, 2]])

In [8]:
##vector는 np.array([...]) 를 사용하여 생성. 

a = np.array([1,2,3])
print(a)

a.shape   ##vector a의 형상을 출력할 땐 shape
a.ndim     ##vector a의 차원을 출력할 땐 ndim

[1 2 3]


1

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a/b)
print(a*b)

#벡터 간 산술 연산은 벡터의 각 원소에 대해서 행해짐

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]


In [11]:
#2차원 행렬 만들기

a = np.array([[1,2,3],[4,5,6]])  ## 큰 대괄호와 작은 대괄호가 있다. 이는 2행 3열의 벡터이다. 

b = a.reshape(3,2)        ##reshape를 하면 행렬의 형상을 바꿀 수 있다. 이 때 원래의 차원 수의 곱이 같아야한다. 2x3행렬은 1x6, 2x3, 3x2, 6x1 행렬로만 바뀔 수 있다. 
b

array([[1, 2],
       [3, 4],
       [5, 6]])