<a href="https://colab.research.google.com/github/2017130744/-neowizard/blob/main/07%20python%20numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
##행렬곱(dot product)
import numpy as np


a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,3],[2,4],[5,6]])
c = np.dot(a,b)

c

#행렬 곱은 행렬의 원소개수가 같아야만 계산할 수 있는 사칙연산의 한계를 벗어나
#행렬곱 조건을 만족하는 다양한 크기의 행렬을 연속으로 만들고
#행렬곱을 연속으로 계산하면서
#결과값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용됨

#예를 들어 입력 행렬 형상이 64x64이고 결과 행렬 형상이 64x10이라면 중간에 dot product를 만족하는 어떤 형상의 행렬이라도 가져올 수 있다.

# (64x64) * (64x256) * (256x512) * (512x64) * (64x10) = (64x10)

array([[20, 29],
       [44, 68]])

In [9]:
#broadcast: 행렬의 사칙 연산은 기본적으로 두 개의 행렬 크기가 같은 경우에만 수행가능.
#그러나 numpy에는 크기가 다른 두 행렬간에도 사칙연산을 할 수 있는데 이를 브로드캐스트라고 지칭
#차원이 작은 쪽이 큰 쪽의 행단위로 반복적으로 크기를 맞춘 후에 계산

a = np.array([[1,2],[3,4]])
b = np.array([5])

#이 때 bradcast를 해주면 b가 [[5,5],[5,5]]가 된다. 

a*b
#이는 사칙연산에만 적용된다. dot product(행렬곱)에서는 적용되지 않는다. 행렬의 사칙연산 곱셈과 행렬곱은 다른 것이다. 




array([[ 5, 10],
       [15, 20]])

In [12]:
#전치행렬: 어떤 행렬의 전치행렬은 원본 행렬의 열은 행으로, 행은 열로 바꾼 것이다. 원본 행렬을 A라고 하면 전치행렬은 AT라고 한다. 
#즉, 1행은 1열로, 2행은 2열로, 3행은 3열로 가는 것이다. 

a = np.array([[1,2,3],[4,5,6]])
b = a.T    ##기존 행렬에 .T를 한다. 
b

c = np.array([1,2,3,4,5])
d = c.T
##이 때 d.shape를 하면 c와 똑같이 (5,) 가 나온다. 그 이유는 벡터(1차원 행렬)는 행과 열을 구분하지 않기 때문이다.
#만약 완전히 전치행렬을 만들고 싶으면 e = c.reshape(1,5)를 한 뒤 f = e.T를 하면 된다. 

(5,)

In [20]:
#행렬의 index

a = np.array([10,20,30,40,50,60]).reshape(3,2)
a[0,0]    ##행렬의 행과 열에 대한 인덱싱이다. 이는 1행 1열을 의미
a[1,0]     ##이는 2행 1열을 의미

a[0:2,1]  #행렬의 인덱싱은 슬라이싱도 가능하다. 여기서 행은 1행과 2행, 열은 1열이므로 1행1열과 2행1열을 의미한다. 

array([20, 40])

In [22]:
#iterator: 행렬의 원소들을 차례대로 읽는 것
a = np.array([[10,20,30,40],[50,60,70,80]])

#보통 다음과 같이 쓴다. 

it = np.nditer(a, flags=['multi_index'], op_flags=['readwrite']) #numpy의 nditer라는 매서드로 구할 수 있다. 안의 변수는 옵션들이다. 

while not it.finished:
  idx = it.multi_index
  print("current value =>", a[idx])
  it.iternext()     #iternext()라는 매서드는 다음 원소로 이동시키는 것이다. 

current value => 10
current value => 20
current value => 30
current value => 40
current value => 50
current value => 60
current value => 70
current value => 80
