<a href="https://colab.research.google.com/github/2017130744/-neowizard/blob/main/19%2C20%2C21%20deep%20learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## 입력신호를 받아 특정 값의 임계점을 넘어서는 경우에 출력을 생성해주는 함수를 활성화함수(activation function)이라고 한다. 
## logitic regression시스템의 sigmoid 함수가 대표적인 활성화함수이다. sigmoid 에서 임계점은 0.5로서, 입력값 합이 0.5보다 크면 1을 출력,ㅣ 크지 않으면 출력 x (0은 출력이 없는 것으로 간주)



In [35]:
## 딥러닝으로 xor 문제 해결하기

import numpy as np

##1. external function(sigmoid, nemirecal_derivative)

def sigmoid(x):
  return 1 / (1+np.exp(-x))


def numerical_derivative(f,x):
  delta_x = 1e-4
  grad = np.zeros_like(x)        

  it = np.nditer(x, flags=['multi_index'], op_flags = ['readwrite'])

  while not it.finished:
    idx = it.multi_index   

    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)    ##f(x + delta_x)

    x[idx] = tmp_val - delta_x
    fx2 = f(x)   ##f(x-delta_x)

    grad[idx] = (fx1 - fx2) / (2*delta_x)

    x[idx] = tmp_val
    it.iternext()

  return grad

In [34]:
## 2. LogicGate class(__init__, __loss_func, error_val)

class LogicGate:

  def __init__(self, gate_name, xdata, tdata):

    self.name = gate_name

    #입력데이터, 정답데이터 초기화
    self.__xdata = xdata.reshape(4,2)  #입력데이터는 (0,0), (0,1), (1,0), (1,1) 4가지이다. 
    self.__tdata = tdata.reshape(4,1)

    # 2층 hidden layer unit : 6개의 노드를 가정, 가중치 W2, 바이어스 b2 초기화
    self.__W2 = np.random.rand(2,6)   
    self.__b2 = np.random.rand(6)

    # 3층 hidden layer unit : 최종 출력값이므로 노드는 1개, 가중치 W3, 바이어스 b3 초기화
    self.__W3 = np.random.rand(6,1)   
    self.__b3 = np.random.rand(1)

    #학습률 learning data 초기화
    self.__learning_rate = 1e-2

    print(self.name + ' object is created')

    #feed forward 를 통하여 손실함수 값 계산
  def feed_forward(self):

     delta = 1e-7   ## log 무한대 발산 방지

     z2 = np.dot(self.__xdata, self.__W2) + self.__b2    ##은닉층의 선형회귀 값 계산
     a2 = sigmoid(z2)                                    ##은닉층의 출력

     z3 = np.dot(a2, self.__W3) + self.__b3              ##출력층의 선형회귀 값
     y = a3 = sigmoid(z3)                                ##출력층의 출력

     #cross-entropy
     return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))

    #외부 출력을위한 손실함수 값 계산
  def loss_val(self):

     delta = 1e-7

     z2 = np.dot(self.__xdata, self.__W2) + self.__b2    ##은닉층의 선형회귀 값 계산
     a2 = sigmoid(z2)                                    ##은닉층의 출력

     z3 = np.dot(a2, self.__W3) + self.__b3              ##출력층의 선형회귀 값
     y = a3 = sigmoid(z3)                                ##출력층의 출력

      #cross-entropy
     return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))


    #수치미분을 이용하여 손실함수가 최소가 될 때까지 학습하는 함수
  def train(self):

      f = lambda x : self.feed_forward()

      print("initial loss value = ", self.loss_val())

      for step in range(10001):

        self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
        self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
        self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
        self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)    ##은닉층마다 그 사이에 있는 가중치와 바이어스를 모두 추가해주어야 한다. 

        if (step % 400 == 0):
          print('step = ', step, 'loss value = ', self.loss_val())

      
    #미래 값 예측 함수
  def predict (self, xdata):
    
     z2 = np.dot(xdata, self.__W2) + self.__b2           ##은닉층의 선형회귀 값 계산
     a2 = sigmoid(z2)                                    ##은닉층의 출력

     z3 = np.dot(a2, self.__W3) + self.__b3              ##출력층의 선형회귀 값
     y = a3 = sigmoid(z3)                                ##출력층의 출력

     if y > 0.5:
       result = 1  #True
      
     else:
       result = 0  #False
       
     return y, result

In [33]:
# AND Gate 객체 생성 및 training

xdata = np.array([[0,0],[0,1],[1,0],[1,1]])
tdata = np.array([0,0,0,1])

and_obj = LogicGate('AND', xdata, tdata)

and_obj.train()


AND object is created
initial loss value =  9.370148565925152
step =  0 loss value =  9.05739425780665
step =  400 loss value =  2.3092721330890233
step =  800 loss value =  2.2199348920425432
step =  1200 loss value =  2.1077934054047227
step =  1600 loss value =  1.938602276456208
step =  2000 loss value =  1.6818778589674874
step =  2400 loss value =  1.3449584588941783
step =  2800 loss value =  1.0166984345633414
step =  3200 loss value =  0.756139674284663
step =  3600 loss value =  0.5641120587805265
step =  4000 loss value =  0.4278397362766977
step =  4400 loss value =  0.33230299278500947
step =  4800 loss value =  0.2647645057092348
step =  5200 loss value =  0.21607670205415047
step =  5600 loss value =  0.18013605389452175
step =  6000 loss value =  0.15296073965388626
step =  6400 loss value =  0.13194483297459486
step =  6800 loss value =  0.11535685646372792
step =  7200 loss value =  0.10202303890307049
step =  7600 loss value =  0.09113041419121809
step =  8000 loss v

In [36]:
#and gate prediction

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for data in test_data:
  print(and_obj.predict(data))

(array([0.00024615]), 0)
(array([0.01435261]), 0)
(array([0.01375151]), 0)
(array([0.97520345]), 1)


In [37]:
#xor gate 검증

xdata = np.array([[0,0],[0,1],[1,0],[1,1]])
tdata = np.array([0,1,1,0])

xor_obj = LogicGate('XOR', xdata, tdata)

xor_obj.train()


XOR object is created
initial loss value =  7.8348554122121765
step =  0 loss value =  7.673828393622834
step =  400 loss value =  2.7688085170198757
step =  800 loss value =  2.7653174338240123
step =  1200 loss value =  2.761372236652676
step =  1600 loss value =  2.7566127577955175
step =  2000 loss value =  2.7506033961723686
step =  2400 loss value =  2.7427860663019166
step =  2800 loss value =  2.732429778557251
step =  3200 loss value =  2.7185800312669612
step =  3600 loss value =  2.7000143439393223
step =  4000 loss value =  2.6752074051606276
step =  4400 loss value =  2.6422974586398276
step =  4800 loss value =  2.5990353290110506
step =  5200 loss value =  2.5427132895607896
step =  5600 loss value =  2.4701113222296005
step =  6000 loss value =  2.377495484654553
step =  6400 loss value =  2.2606323898726144
step =  6800 loss value =  2.1149639846235617
step =  7200 loss value =  1.9369651590237527
step =  7600 loss value =  1.7281211218515375
step =  8000 loss value = 

In [38]:
#xor gate prediction

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for data in test_data:
  print(xor_obj.predict(data))


  ##딥러닝을 이용하면 xor 도 해결이 가능하다. 

(array([0.04886691]), 0)
(array([0.85623553]), 1)
(array([0.84634137]), 1)
(array([0.2248097]), 0)
